//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPL
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.policies = new HashSet<policy>();
        }
    
        public int car_id { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public int driver_id { get; set; }
        public string model { get; set; }
        public int year_manufacture { get; set; }
        public string reg_number { get; set; }
        public string stc_number { get; set; }
        public string pts_number { get; set; }
    
        public virtual car_brands car_brands { get; set; }
        public virtual car_categories car_categories { get; set; }
        public virtual driver driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy> policies { get; set; }
    }
}
