//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTPL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTPLEntities : DbContext
    {
        private static MTPLEntities _context;
        public MTPLEntities()
            : base("name=MTPLEntities")
        {
        }

        public static MTPLEntities GetContext()
        {
            if (_context == null)
            {
                _context = new MTPLEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car_brands> car_brands { get; set; }
        public virtual DbSet<car_categories> car_categories { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<policy> policies { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
